defaults: &defaults
  working_directory: ~/code
  docker:
  - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m
  parallelism: 2

version: 2
jobs:
  "Dependencies":
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - persist_to_workspace:
        root: ~/code
        paths:
        - ./*
  "Lint":
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Lint
        command: ./gradlew lint
    - store_artifacts:
        path: app/build/reports
        destination: reports
  "Unit_tests":
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Unit Tests
        command: ./gradlew test
    - store_test_results:
        path: app/build/test-results
  "Build":
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Build
        command: ./gradlew clean assembleRelease
    - store_artifacts:
        path: app/build/outputs/apk/
        destination: release
    - persist_to_workspace:
        root: ~/code
        paths:
        - ./*
  "Fabric_prop":
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/code/app
    - run:
        name: Generate fabric.properties
        command: echo "apiSecret=${FABRIC_SECRET}\napiKey=${FABRIC_KEY}" > fabric.properties
    - persist_to_workspace:
        root: ~/code
        paths:
          - app/fabric.properties
  "Fabric_deploy":
    <<: *defaults
    working_directory: ~/code
    steps:
    - attach_workspace:
        at: ~/code
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - deploy:
        name: Deploy Fabric
        command: ./gradlew crashlyticsUploadDistributionRelease
workflows:
  version: 2
  build:
    jobs:
      - "Dependencies"
      - "Unit_tests":
          requires:
            - "Dependencies"
      - "Lint":
          requires:
            - "Dependencies"
      - "Build":
          requires:
            - "Lint"
            - "Unit_tests"
      - "Fabric_prop"
      - "Fabric_deploy":
          requires:
            - "Build"
            - "Fabric_prop"
